# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='castomerPhone',
            new_name='customerName',
        ),
        migrations.RemoveField(
            model_name='order',
            name='castomerName',
        ),
        migrations.AddField(
            model_name='order',
            name='customerPhone',
            field=models.CharField(blank=True, default=None, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='orderDescription',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
