# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20170610_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='coil',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productincart',
            name='winding',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
